export type CountryOption = {
    name: string
    code: string
    flag: string
    popular?: boolean
}

export const COUNTRIES: CountryOption[] = [
    { name: "US Dollar", code: "USD", flag: "/images/flags/us.webp", popular: true },
    { name: "Euro", code: "EUR", flag: "/images/flags/eu.webp", popular: true },
    { name: "British Pound", code: "GBP", flag: "/images/flags/gb.webp", popular: true },
    { name: "Japanese Yen", code: "JPY", flag: "/images/flags/jp.webp" },
    { name: "Australian Dollar", code: "AUD", flag: "/images/flags/au.webp" },
    { name: "Canadian Dollar", code: "CAD", flag: "/images/flags/ca.webp" },
    { name: "Swiss Franc", code: "CHF", flag: "/images/flags/ch.webp" },
    { name: "Chinese Yuan", code: "CNY", flag: "/images/flags/cn.webp" },
    { name: "Swedish Krona", code: "SEK", flag: "/images/flags/se.webp" },
    { name: "New Zealand Dollar", code: "NZD", flag: "/images/flags/nz.webp" },
    { name: "UAE Dirham", code: "AED", flag: "/images/flags/ae.webp" },
    { name: "Argentine Peso", code: "ARS", flag: "/images/flags/ar.webp" },
    { name: "Bangladeshi Taka", code: "BDT", flag: "/images/flags/bd.webp" },
    { name: "Bulgarian Lev", code: "BGN", flag: "/images/flags/bg.webp" },
    { name: "Bahraini Dinar", code: "BHD", flag: "/images/flags/bh.webp" },
    { name: "Brazilian Real", code: "BRL", flag: "/images/flags/br.webp" },
    { name: "Chilean Peso", code: "CLP", flag: "/images/flags/cl.webp" },
    { name: "Colombian Peso", code: "COP", flag: "/images/flags/co.webp" },
    { name: "Czech Koruna", code: "CZK", flag: "/images/flags/cz.webp" },
    { name: "Danish Krone", code: "DKK", flag: "/images/flags/dk.webp" },
    { name: "Egyptian Pound", code: "EGP", flag: "/images/flags/eg.webp" },
    { name: "Hong Kong Dollar", code: "HKD", flag: "/images/flags/hk.webp" },
    { name: "Honduran Lempira", code: "HNL", flag: "/images/flags/hn.webp" },
    { name: "Haitian Gourde", code: "HTG", flag: "/images/flags/ht.webp" },
    { name: "Hungarian Forint", code: "HUF", flag: "/images/flags/hu.webp" },
    { name: "Indian Rupee", code: "INR", flag: "/images/flags/in.webp" },
    { name: "Indonesian Rupiah", code: "IDR", flag: "/images/flags/id.webp" },
    { name: "Icelandic Krona", code: "ISK", flag: "/images/flags/is.webp" },
    { name: "Jordanian Dinar", code: "JOD", flag: "/images/flags/jo.webp" },
    { name: "Kenyan Shilling", code: "KES", flag: "/images/flags/ke.webp" },
    { name: "Kuwaiti Dinar", code: "KWD", flag: "/images/flags/kw.webp" },
    { name: "Lebanese Pound", code: "LBP", flag: "/images/flags/lb.webp" },
    { name: "East Caribbean Dollar", code: "XCD", flag: "/images/flags/lc.webp" },
    { name: "Sri Lankan Rupee", code: "LKR", flag: "/images/flags/lk.webp" },
    { name: "Mexican Peso", code: "MXN", flag: "/images/flags/mx.webp" },
    { name: "Moroccan Dirham", code: "MAD", flag: "/images/flags/ma.webp" },
    { name: "Malaysian Ringgit", code: "MYR", flag: "/images/flags/my.webp" },
    { name: "Nigerian Naira", code: "NGN", flag: "/images/flags/ng.webp" },
    { name: "Norwegian Krone", code: "NOK", flag: "/images/flags/no.webp" },
    { name: "Nepalese Rupee", code: "NPR", flag: "/images/flags/np.webp" },
    { name: "Omani Rial", code: "OMR", flag: "/images/flags/om.webp" },
    { name: "Pakistani Rupee", code: "PKR", flag: "/images/flags/pk.webp" },
    { name: "Philippine Peso", code: "PHP", flag: "/images/flags/ph.webp" },
    { name: "Peruvian Sol", code: "PEN", flag: "/images/flags/pe.webp" },
    { name: "Polish Zloty", code: "PLN", flag: "/images/flags/pl.webp" },
    { name: "Qatari Riyal", code: "QAR", flag: "/images/flags/qa.webp" },
    { name: "Romanian Leu", code: "RON", flag: "/images/flags/ro.webp" },
    { name: "Russian Ruble", code: "RUB", flag: "/images/flags/ru.webp" },
    { name: "Saudi Riyal", code: "SAR", flag: "/images/flags/sa.webp" },
    { name: "Singapore Dollar", code: "SGD", flag: "/images/flags/sg.webp" },
    { name: "South African Rand", code: "ZAR", flag: "/images/flags/za.webp" },
    { name: "South Korean Won", code: "KRW", flag: "/images/flags/kr.webp" },
    { name: "Thai Baht", code: "THB", flag: "/images/flags/th.webp" },
    { name: "New Taiwan Dollar", code: "TWD", flag: "/images/flags/tw.webp" },
    { name: "Turkish Lira", code: "TRY", flag: "/images/flags/tr.webp" },
    { name: "Ukrainian Hryvnia", code: "UAH", flag: "/images/flags/ua.webp" },
    { name: "Vietnamese Dong", code: "VND", flag: "/images/flags/vn.webp" },
]